version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_PORT: 3000
      NODE_ENV: production

      # Credenciales de la BD
      DB_HOST: ep-old-violet-a2yo3r33.eu-central-1.aws.neon.tech
      DB_PORT: 5432
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_pL0h5YxfTumS
      DB_NAME: sad-tpi